version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: aula-spring
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: aula-spring
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
  keycloak:
    image: keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
    ports:
      - "8243:8080"
    command: start-dev