com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: http://localhost:8243/realms/master
          username-claim: preferred_username
          authorities:
            - path: $.realm_access.roles
            - path: $.resource_access.*.roles
logging:
  level:
    org:
      springframework:
        security: DEBUG
        boot: INFO
#          oauth2-logout:
#            cognito-user:
#              uri: https://spring-addons.auth.us-west-2.amazoncognito.com/logout
#              client-id-request-param: client_id
#              post-logout-uri-request-param: logout_uri
#            auth0-user:
#              uri: ${auth0-issuer}v2/logout
#              client-id-request-param: client_id
#              post-logout-uri-request-param: returnTo